### ISSUE TITLE
Components via webpack

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/algolia-technical-test#2]
Currently I load the components into the html directly, and not as ES6 modules that are `import`ed when necessary. If I'd change that I'll have to use webpack, but then I can also depend on certain Tachyons modules in each of the components.

What I think is a disadvantage of this is that webpack isn't always too streamlined to work with, and will have a higher file size, because it needs to deal with things like circular dependencies and dependency dedups.

Which is why I'll keep it like this now.

**Comment by vvo** [comment]
It's good for us too :)

**Comment by vvo** [comment]
There seems to be a way to write vuejs components with webpack, but honestly this is tooling related so if you want to fix it: great! But it's not mandatory in this test

**Comment by Haroenv** [comment]
Yep, I tried to use it first, but had some weird issues and I decided that it wasn't a necessity.
